### ISSUE TITLE
TODO: Convert to Maven

### ISSUE THREAD

**Issue by EricCanull** [EricCanull/fxexperience2#5]

**Comment by malikoski** [comment]
[fxexperience-maven.zip](https://github.com/EricCanull/fxexperience-2/files/983446/fxexperience-maven.zip)

**Comment by EricCanull** [comment]
Malikoski, I was able to convert it in just a little over 30 mins using the template zip you uploaded.  Project should be build ready as of 05/19/17.  tks!
