### ISSUE TITLE
Ready For Release?

### ISSUE THREAD

**Issue by APMKimpton** [EricCanull/fxexperience2#6]
Hello,

Is the newer version of this ready / working for Java 8 / 9 yet? If so, should I just clone this repo and export it on my PC or do you have an executable already?

Cheers,
APMKimpton

**Comment by EricCanull** [comment]
APMKimpton,

Yes, it's JavaFX 8 / 9 ready.  There isn't an executable release for this version yet since its still beta.  I make frequent updates, sometimes 3 or 4 per day so just be aware of that.  You shouldn't have any problems building it using a clone.  If you do, let me know  

tks!
Eric C.
